blank_issues_enabled: false
contact_links:
  - name: âš ï¸ Application issue
    url: https://github.com/komikku-app/anikku/issues/new/choose
    about: Issues and requests about the app itself should be opened in the tachiyomi repository instead
  - name: ğŸ“¦ Aniyomi extensions
    url: https://yuzono.github.io/extensions-aniyomi
    about: List of all available extensions with download links
  - name: ğŸ–¥ï¸ Anikku website
    url: https://anikku-app.github.io/help/
    about: Guides, troubleshooting, and answers to common questions
  - name: Anikku app GitHub repository
    url: https://github.com/komikku-app/anikku
    about: Issues about the app itself should be opened here instead.
