name: Auto Merge Upstream

on:
  # Monthly
  schedule:
    - cron: '0 0 * * *'
  # Manual trigger
  workflow_dispatch:
    inputs:

jobs:
  update-dark25:
    name: Update Dark25
    runs-on: ubuntu-latest

    steps:
      - name: Set env
        run: |
          echo "UPSTREAM_URL=https://github.com/Dark25/aniyomi-extensions.git" >> $GITHUB_ENV
          echo "UPSTREAM_BRANCH=master" >> $GITHUB_ENV
          echo "LOCAL_BRANCH=dark25" >> $GITHUB_ENV
          echo "MERGE_BRANCH=master" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{env.LOCAL_BRANCH}}
          token: ${{ secrets.BOT_PAT }}

      - name: Add remote repository
        run: git remote add upstream ${{env.UPSTREAM_URL}}

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Merge upstream changes
        run: git merge upstream/${{env.UPSTREAM_BRANCH}}

      - name: Push changes to repository
        run: git push origin ${{env.LOCAL_BRANCH}}

      - name: Import GPG key
        id: import-gpg
        uses: crazy-max/ghaction-import-gpg@v6  # v6.1.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: GPG user IDs
        run: |
          echo "fingerprint: ${{ steps.import-gpg.outputs.fingerprint }}"
          echo "keyid:       ${{ steps.import-gpg.outputs.keyid }}"
          echo "name:        ${{ steps.import-gpg.outputs.name }}"
          echo "email:       ${{ steps.import-gpg.outputs.email }}"

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{env.MERGE_BRANCH}}
          token: ${{ secrets.BOT_PAT }}

      - name: Merge ${{env.LOCAL_BRANCH}}
        run: git merge origin/${{env.LOCAL_BRANCH}}

      - name: Push to repository
        run: git push origin ${{env.MERGE_BRANCH}}

  update-kohi-den:
    name: Update Kohi-den
    runs-on: ubuntu-latest

    steps:
      - name: Set env
        run: |
          echo "UPSTREAM_URL=https://github.com/Kohi-den/extensions-source.git" >> $GITHUB_ENV
          echo "UPSTREAM_BRANCH=main" >> $GITHUB_ENV
          echo "LOCAL_BRANCH=kohiden" >> $GITHUB_ENV
          echo "MERGE_BRANCH=main" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{env.LOCAL_BRANCH}}
          token: ${{ secrets.BOT_PAT }}

      - name: Add remote repository
        run: git remote add upstream ${{env.UPSTREAM_URL}}

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Merge upstream changes
        run: git merge upstream/${{env.UPSTREAM_BRANCH}}

      - name: Push changes to repository
        run: git push origin ${{env.LOCAL_BRANCH}}

      - name: Import GPG key
        id: import-gpg
        uses: crazy-max/ghaction-import-gpg@v6  # v6.1.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: GPG user IDs
        run: |
          echo "fingerprint: ${{ steps.import-gpg.outputs.fingerprint }}"
          echo "keyid:       ${{ steps.import-gpg.outputs.keyid }}"
          echo "name:        ${{ steps.import-gpg.outputs.name }}"
          echo "email:       ${{ steps.import-gpg.outputs.email }}"

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{env.MERGE_BRANCH}}
          token: ${{ secrets.BOT_PAT }}

      - name: Merge ${{env.LOCAL_BRANCH}}
        run: git merge origin/${{env.LOCAL_BRANCH}}

      - name: Push to repository
        run: git push origin ${{env.MERGE_BRANCH}}